server:
    port: 8088

spring:
    datasource:
        url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;
        driver-class-name: org.h2.Driver
        username: sa
        password: sa
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
    h2:
        console:
            enabled: true
            path: /h2-console

flyway:
    url: jdbc:h2:mem:test
    user: sa
    password: sa